name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install CMake and g++
      run: |
        sudo apt update && sudo apt install -y cmake g++
        sudo apt install -y cmake g++ build-essential \
                        libeigen3-dev catch2

    - name: Configure Cmake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build 

    - name: Test
      run: ctest --test-dir build --output-on-failure
